schema {
    query: Query
    mutation: Mutation
}
type Todo {
    id: ID!
    userId: ID!
    text: String!
    completed: Boolean!
    timeAdded: Long!
}

type Query {   
    todos: [Todo]
}

type Mutation {
    addTodo(text: String!, completed:Boolean): Todo
    updateTodo(id: ID!, text: String!, completed:Boolean): Todo
    deleteTodo(id: ID!): Todo
}